<template>
  <div class="sales-report-container">
    <!-- Business Info Section -->
    <div class="business-info">
      <h1 class="business-name">{{ businessName }}</h1>
      <p class="report-meta">Generated by: {{ userName }} | {{ currentDateTime }}</p>
    </div>

    <!-- Date Range and Export Section -->
    <div class="controls-section">
      <!-- Date Range Dropdown -->
      <div class="date-filter" ref="dateDropdown">
        <button class="filter-btn" @click="toggleDateDropdown">
          <i class="fas fa-calendar-alt"></i>
          <span>{{ selectedRange }}</span>
          <i class="fas fa-chevron-down" :class="{ 'rotate': showDateDropdown }"></i>
        </button>
        
        <div v-if="showDateDropdown" class="dropdown-menu date-menu">
          <div class="dropdown-options">
            <button 
              v-for="(label, range) in dateRanges" 
              :key="range"
              class="dropdown-item"
              :class="{ 'active': selectedRange === label }"
              @click="selectDateRange(range)"
            >
              {{ label }}
            </button>
          </div>
          
          <div v-if="showCustomRange" class="custom-range">
            <div class="custom-range-header">Select Date Range</div>
            <div class="range-inputs">
              <div class="input-group">
                <label>Start Date</label>
                <input type="date" v-model="dateRange.start" :max="dateRange.end">
              </div>
              <div class="input-group">
                <label>End Date</label>
                <input type="date" v-model="dateRange.end" :min="dateRange.start">
              </div>
            </div>
            <button class="apply-btn" @click="applyCustomRange">Apply</button>
          </div>
        </div>
      </div>

      <!-- Export Dropdown -->
      <div class="export-filter" ref="exportDropdown">
        <button 
          type="button"
          class="filter-btn export-btn" 
          @click="toggleExportDropdown"
        >
          <i class="fas fa-download"></i>
          <span>Export</span>
          <i class="fas fa-chevron-down" :class="{ 'rotate': showExportDropdown }"></i>
        </button>
        
        <div v-show="showExportDropdown" class="dropdown-menu export-menu">
          <button 
            type="button"
            class="dropdown-item" 
            @click="handleExportToPDF"
          >
            <i class="fas fa-file-pdf"></i>
            <span>Export to PDF</span>
          </button>
          <button 
            type="button"
            class="dropdown-item" 
            @click="handleExportToExcel"
          >
            <i class="fas fa-file-excel"></i>
            <span>Export to Excel</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
      <div class="summary-card">
        <i class="fas fa-shopping-cart summary-icon"></i>
        <div class="summary-details">
          <h3>Total Orders</h3>
          <p class="summary-value">{{ totalOrders }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-box summary-icon"></i>
        <div class="summary-details">
          <h3>Total Products</h3>
          <p class="summary-value">{{ totalProducts }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-receipt summary-icon"></i>
        <div class="summary-details">
          <h3>Total Tax</h3>
          <p class="summary-value">{{ formatCurrency(totalTax) }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-money-bill-wave summary-icon"></i>
        <div class="summary-details">
          <h3>Total Revenue</h3>
          <p class="summary-value">{{ formatCurrency(totalRevenue) }}</p>
        </div>
      </div>
    </div>

    <!-- Data Table Section -->
    <div v-if="loading" class="loading-state">
      Loading sales data...
    </div>

    <!-- No Data State -->
    <div v-else-if="salesData.length === 0" class="no-data-state">
      No sales data available for the selected period.
    </div>

    <!-- Data Table -->
    <div v-else class="data-table-container">
      <table class="data-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Orders</th>
            <th>Products Sold</th>
            <th>Tax</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in filteredData" :key="row.order_date">
            <td>{{ formatDate(row.order_date) }}</td>
            <td>{{ row.order_count }}</td>
            <td>{{ row.products_sold }}</td>
            <td>{{ formatCurrency(row.tax) }}</td>
            <td>{{ formatCurrency(row.total) }}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"><strong>Totals</strong></td>
            <td><strong>{{ totalProducts }}</strong></td>
            <td><strong>{{ formatCurrency(totalTax) }}</strong></td>
            <td><strong>{{ formatCurrency(totalRevenue) }}</strong></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</template>

<style scoped>
.sales-report-container {
  background: #ffffff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  padding: 24px;
  margin: 24px;
}

/* Header Styling */
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 32px;
}

.title-section {
  display: flex;
  flex-direction: column;
}

.title {
  font-size: 24px;
  font-weight: 600;
  color: #2c3e50;
  margin: 0;
}

.subtitle {
  color: #6c757d;
  margin: 4px 0 0 0;
  font-size: 14px;
}

/* Export Button Styling */
.export-dropdown {
  position: relative;
  z-index: 1000;
}

.export-button {
  background: #2196F3;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 2px 4px rgba(33, 150, 243, 0.2);
  white-space: nowrap;
}

.export-button:hover {
  background: #1976D2;
  transform: translateY(-1px);
  box-shadow: 0 4px 8px rgba(33, 150, 243, 0.3);
}

.fa-chevron-down {
  transition: transform 0.3s ease;
}

.fa-chevron-down.rotate {
  transform: rotate(180deg);
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  right: 0;
  margin-top: 8px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  min-width: 200px;
  border: 1px solid rgba(0, 0, 0, 0.1);
  z-index: 1001;
}

.dropdown-item {
  display: flex;
  align-items: center;
  width: 100%;
  padding: 12px 16px;
  border: none;
  background: none;
  color: #2c3e50;
  cursor: pointer;
  transition: all 0.2s ease;
  text-align: left;
}

.dropdown-item:hover {
  background: #f0f7ff;
  color: #2196F3;
}

.dropdown-item:not(:last-child) {
  border-bottom: 1px solid #eee;
}

/* Fade transition */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

/* Filters Section */
.filters-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
  margin-bottom: 32px;
}

.filter-label {
  display: block;
  margin-bottom: 8px;
  color: #2c3e50;
  font-weight: 500;
  font-size: 14px;
}

.filter-select, .date-input, .search-input {
  width: 100%;
  padding: 10px 16px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  font-size: 14px;
  color: #2c3e50;
  transition: all 0.3s ease;
}

.filter-select:focus, .date-input:focus, .search-input:focus {
  border-color: #4CAF50;
  outline: none;
  box-shadow: 0 0 0 3px rgba(76, 175, 80, 0.1);
}

.search-input-wrapper {
  position: relative;
}

.search-icon {
  position: absolute;
  left: 16px;
  top: 50%;
  transform: translateY(-50%);
  color: #6c757d;
}

.search-input {
  padding-left: 44px;
}

/* Table Styling */
.table-wrapper {
  overflow-x: auto;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.table-header {
  background: #f8f9fa;
  padding: 16px;
  font-weight: 600;
  color: #2c3e50;
  text-align: left;
  cursor: pointer;
  transition: background 0.2s ease;
}

.table-header:hover {
  background: #e9ecef;
}

.header-content {
  display: flex;
  align-items: center;
  gap: 8px;
}

.sort-icon {
  color: #4CAF50;
}

tbody tr {
  border-bottom: 1px solid #e2e8f0;
}

tbody tr:last-child {
  border-bottom: none;
}

td {
  padding: 16px;
  color: #2c3e50;
}

tbody tr:hover {
  background: #f8f9fa;
}

@media (max-width: 768px) {
  .header {
    flex-direction: column;
    align-items: stretch;
    gap: 16px;
  }

  .export-dropdown {
    width: 100%;
  }

  .export-button {
    width: 100%;
    justify-content: center;
  }

  .dropdown-menu {
    width: 100%;
  }
}

/* Ensure dropdown is visible */
.export-dropdown {
  position: relative !important;
}

.dropdown-menu {
  display: block;
  visibility: visible;
  opacity: 1;
}

/* Debug styles */
.dropdown-menu[style*="display: none"] {
  display: block !important;
  visibility: hidden;
  opacity: 0;
}

.dropdown-menu {
  background: red !important;
  z-index: 9999 !important;
  position: fixed !important;
  top: 100px !important;
  right: 100px !important;
}

.business-info {
  text-align: center;
  margin-bottom: 2rem;
}

.business-name {
  font-size: 2rem;
  color: #2c3e50;
  margin-bottom: 0.5rem;
}

.report-meta {
  color: #6c757d;
  font-size: 0.9rem;
}

.summary-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.summary-card {
  background: white;
  border-radius: 10px;
  padding: 1.5rem;
  display: flex;
  align-items: center;
  gap: 1rem;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  transition: transform 0.2s ease;
}

.summary-card:hover {
  transform: translateY(-2px);
}

.summary-icon {
  font-size: 2rem;
  color: #2196F3;
  background: rgba(33, 150, 243, 0.1);
  padding: 1rem;
  border-radius: 50%;
}

.summary-details h3 {
  margin: 0;
  font-size: 0.9rem;
  color: #6c757d;
}

.summary-value {
  margin: 0.25rem 0 0;
  font-size: 1.5rem;
  font-weight: 600;
  color: #2c3e50;
}

@media (max-width: 768px) {
  .summary-section {
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  }
}

.data-table-container {
  margin-top: 2rem;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.data-table th,
.data-table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #eee;
}

.data-table th {
  background: #f8f9fa;
  font-weight: 600;
  color: #2c3e50;
}

.data-table tbody tr:hover {
  background: #f8f9fa;
}

.data-table tfoot {
  font-weight: 600;
  background: #f8f9fa;
}

.loading-state,
.no-data-state {
  text-align: center;
  padding: 2rem;
  color: #6c757d;
  font-style: italic;
}

.controls-section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1.5rem;
  position: relative;
}

.date-filter, .export-filter {
  position: relative;
}

.filter-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  font-size: 0.875rem;
  color: #333;
  cursor: pointer;
  min-width: 150px;
  justify-content: space-between;
}

.export-btn {
  background: #2196F3;
  color: white;
  border: none;
}

.dropdown-menu {
  position: absolute;
  top: calc(100% + 0.25rem);
  left: 0;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  z-index: 1000;
}

.date-menu {
  width: 240px;
}

.export-menu {
  width: 100%;
  min-width: 180px;
}

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.5rem 1rem;
  border: none;
  background: none;
  text-align: left;
  font-size: 0.875rem;
  color: #333;
  cursor: pointer;
}

.dropdown-item:hover {
  background: #f5f5f5;
}

.dropdown-item.active {
  background: #e3f2fd;
  color: #2196F3;
}

.custom-range {
  border-top: 1px solid #ddd;
  padding: 1rem;
  background: #f8f9fa;
}

.custom-range-header {
  font-weight: 500;
  margin-bottom: 0.75rem;
  color: #333;
}

.range-inputs {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.input-group {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.input-group label {
  font-size: 0.75rem;
  color: #666;
}

.input-group input {
  padding: 0.375rem;
  border: 1px solid #ddd;
  border-radius: 0.25rem;
  font-size: 0.875rem;
}

.apply-btn {
  width: 100%;
  margin-top: 0.75rem;
  padding: 0.5rem;
  background: #2196F3;
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-size: 0.875rem;
}

.apply-btn:hover {
  background: #1976D2;
}

.rotate {
  transform: rotate(180deg);
}

@media (max-width: 768px) {
  .controls-section {
    flex-direction: column;
  }

  .date-filter, .export-filter {
    width: 100%;
  }

  .filter-btn {
    width: 100%;
  }

  .dropdown-menu {
    width: 100%;
  }
}

/* Update these specific styles */
.export-filter {
  position: relative;
  display: inline-block;
}

.export-btn {
  min-width: 120px; /* Adjust this value based on your needs */
  white-space: nowrap;
}

.export-menu {
  position: absolute;
  top: 100%;
  right: 0; /* Align to right */
  width: 100%; /* Match button width */
  min-width: fit-content;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  z-index: 1000;
  margin-top: 0.25rem;
}

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  width: 100%;
  border: none;
  background: none;
  text-align: left;
  cursor: pointer;
  white-space: nowrap;
}

.dropdown-item:hover {
  background: #f5f5f5;
}
</style>

<script>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import axios from 'axios'
import * as XLSX from 'xlsx'
import jsPDF from 'jspdf'
import 'jspdf-autotable'

export default {
  name: 'SalesReportComponent',
  
  data() {
    // Debug log to check Laravel user data
    console.log('Window Laravel:', window.Laravel);
    console.log('User data:', window.Laravel?.user);
    
    return {
      salesData: ref([]),
      searchQuery: ref(''),
      selectedDateFilter: ref('today'),
      sortColumn: ref('order_date'),
      sortDirection: ref('desc'),
      dateRange: {
        start: new Date().toISOString().split('T')[0],
        end: new Date().toISOString().split('T')[0]
      },
      showDropdown: false,
      exportButton: ref(null),
      dropdownMenu: ref(null),
      currencySettings: ref({
        symbol: 'KES',
        position: 'before' // or 'after'
      }),

      dateFilters: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'Last 7 Days', value: 'last7days' },
        { label: 'Last 30 Days', value: 'last30days' },
        { label: 'This Month', value: 'thisMonth' },
        { label: 'Last Month', value: 'lastMonth' },
        { label: 'Custom Range', value: 'custom' }
      ],

      tableHeaders: [
        { label: 'Order Date', value: 'order_date' },
        { label: 'Number of Orders', value: 'order_count' },
        { label: 'Products Sold', value: 'products_sold' },
        { label: 'Tax', value: 'tax' },
        { label: 'Total', value: 'total' }
      ],

      businessName: localStorage.getItem('businessName') || '',
      userName: '',
      currentDateTime: new Date().toLocaleString(),
      currency: localStorage.getItem('currency') || '',
      currencySymbol: '',
      loading: false,
      showDateDropdown: false,
      showCustomRange: false,
      selectedRange: 'Today',
      dateRanges: {
        today: 'Today',
        yesterday: 'Yesterday',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        thisYear: 'This Year',
        custom: 'Custom Range'
      },
      showExportDropdown: false
    }
  },

  computed: {
    // Filter and Sort Logic
    filteredData() {
      return this.salesData;
    },

    totalProducts() {
      return this.filteredData.reduce((sum, row) => sum + (Number(row.products_sold) || 0), 0);
    },
    
    totalOrders() {
      return this.filteredData.reduce((sum, row) => sum + (Number(row.order_count) || 0), 0);
    },
    
    totalRevenue() {
      return this.filteredData.reduce((sum, row) => sum + (Number(row.total) || 0), 0);
    },
    
    totalTax() {
      return this.filteredData.reduce((sum, row) => sum + (Number(row.tax) || 0), 0);
    },

    currencyLabel() {
      return this.currency || 'KES';
    }
  },

  methods: {
    // Add method to set user name
    setUserName() {
      if (window.Laravel && window.Laravel.user) {
        this.userName = window.Laravel.user.name;
        console.log('User name set:', this.userName);
      } else {
        this.userName = 'Unknown User';
        console.warn('User data not found');
      }
    },

    // Fetch Settings
    async fetchSettings() {
      try {
        const response = await axios.get('/api/settings');
        console.log('Settings API response:', response.data);
        
        if (response.data.status === 'success' && response.data.settings) {
          const settings = response.data.settings;
          
          // Update and persist business name and currency
          this.businessName = settings.business_name || 'Default Business';
          this.currency = settings.currency || 'KES';
          
          // Store in localStorage
          localStorage.setItem('businessName', this.businessName);
          localStorage.setItem('currency', this.currency);
          
          console.log('Settings updated:', {
            businessName: this.businessName,
            currency: this.currency
          });
        }
      } catch (error) {
        console.error('Error fetching settings:', error);
        // Use cached values from localStorage if available
        this.businessName = localStorage.getItem('businessName') || 'Default Business';
        this.currency = localStorage.getItem('currency') || 'KES';
      }
    },

    // Fetch Data
    async fetchSalesData() {
      try {
        this.loading = true;
        console.log('Fetching with dates:', this.dateRange);

        const response = await axios.get('/api/sales-report', {
          params: {
            start_date: this.dateRange.start,
            end_date: this.dateRange.end
          }
        });

        if (Array.isArray(response.data)) {
          this.salesData = response.data;
          console.log('Sales data loaded:', this.salesData);
        } else {
          console.error('Unexpected response format:', response.data);
          this.salesData = [];
        }
      } catch (error) {
        console.error('Error fetching sales data:', error);
        this.salesData = [];
      } finally {
        this.loading = false;
      }
    },

    // Format Currency with Settings
    formatCurrency(amount) {
      try {
        const num = Number(amount);
        if (isNaN(num)) return `${this.currency} 0.00`;
        return new Intl.NumberFormat('en-KE', {
          style: 'currency',
          currency: this.currency || 'KES',
          minimumFractionDigits: 2,
          maximumFractionDigits: 2
        }).format(num);
      } catch (error) {
        console.error('Currency formatting error:', error);
        return `${this.currency} 0.00`;
      }
    },

    toggleDropdown() {
      this.showDateDropdown = !this.showDateDropdown;
      if (this.showExportDropdown) this.showExportDropdown = false;
    },

    handleClickOutside(event) {
      const dropdown = this.$refs.exportDropdown;
      if (dropdown && !dropdown.contains(event.target)) {
        this.showDropdown = false;
      }
    },

    async handleExportToPDF() {
      try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        
        // Add business header
        doc.setFontSize(16);
        const businessText = this.businessName || 'Sales Report';
        const textWidth = doc.getTextWidth(businessText);
        const xPosition = (pageWidth - textWidth) / 2;
        doc.text(businessText, xPosition, 20);
        
        // Add metadata
        doc.setFontSize(10);
        doc.text(`Generated by: ${this.userName}`, 15, 30);
        doc.text(`Date: ${new Date().toLocaleString()}`, 15, 35);
        
        // Add summary section
        doc.setFontSize(12);
        doc.text('Summary', 15, 45);
        
        const summaryData = [
          ['Total Orders', this.totalOrders.toString()],
          ['Total Products', this.totalProducts.toString()],
          ['Total Tax', this.formatCurrency(this.totalTax)],
          ['Total Revenue', this.formatCurrency(this.totalRevenue)]
        ];

        // Add summary table
        doc.autoTable({
          startY: 50,
          head: [['Metric', 'Value']],
          body: summaryData,
          theme: 'grid',
          styles: { fontSize: 10 },
          headStyles: { fillColor: [33, 150, 243] }
        });

        // Add main data table
        const tableData = this.salesData.map(row => [
          this.formatDate(row.order_date),
          row.order_count.toString(),
          row.products_sold.toString(),
          this.formatCurrency(row.tax),
          this.formatCurrency(row.total)
        ]);

        doc.autoTable({
          startY: doc.previousAutoTable.finalY + 15,
          head: [['Date', 'Orders', 'Products', 'Tax', 'Total']],
          body: tableData,
          theme: 'grid',
          styles: { fontSize: 8 },
          headStyles: { fillColor: [33, 150, 243] }
        });

        // Generate filename
        const fileName = `${this.businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sales_report_${new Date().toISOString().split('T')[0]}.pdf`;
        
        doc.save(fileName);
        this.showExportDropdown = false;
      } catch (error) {
        console.error('PDF export failed:', error);
        alert('Failed to export PDF. Please try again.');
      }
    },

    async handleExportToExcel() {
      try {
        // Create workbook
        const wb = XLSX.utils.book_new();
        
        // Add summary worksheet
        const summaryData = [
          ['Business Name:', this.businessName],
          ['Generated By:', this.userName],
          ['Date:', new Date().toLocaleString()],
          [''],
          ['Summary'],
          ['Total Orders:', this.totalOrders],
          ['Total Products:', this.totalProducts],
          ['Total Tax:', this.formatCurrency(this.totalTax)],
          ['Total Revenue:', this.formatCurrency(this.totalRevenue)]
        ];
        
        const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
        XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

        // Add details worksheet
        const wsData = this.salesData.map(row => ({
          'Date': this.formatDate(row.order_date),
          'Orders': row.order_count,
          'Products': row.products_sold,
          'Tax': this.formatCurrency(row.tax),
          'Total': this.formatCurrency(row.total)
        }));
        
        const wsDetails = XLSX.utils.json_to_sheet(wsData);
        XLSX.utils.book_append_sheet(wb, wsDetails, "Details");

        // Generate filename and save
        const fileName = `${this.businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sales_report_${new Date().toISOString().split('T')[0]}.xlsx`;
        XLSX.writeFile(wb, fileName);
        
        this.showExportDropdown = false;
      } catch (error) {
        console.error('Excel export failed:', error);
        alert('Failed to export Excel file. Please try again.');
      }
    },

    formatDate(date) {
      try {
        return new Date(date).toLocaleDateString();
      } catch (error) {
        return date;
      }
    },

    formatCurrency(amount) {
      try {
        return new Intl.NumberFormat('en-KE', {
          style: 'currency',
          currency: this.currency || 'KES'
        }).format(amount);
      } catch (error) {
        return `${this.currency} ${amount}`;
      }
    },

    // Utility Functions
    isSameDay(date1, date2) {
      return date1.getDate() === date2.getDate() &&
             date1.getMonth() === date2.getMonth() &&
             date1.getFullYear() === date2.getFullYear()
    },

    sortBy(column) {
      if (this.sortColumn === column) {
        this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc'
      } else {
        this.sortColumn = column
        this.sortDirection = 'asc'
      }
    },

    async fetchBusinessInfo() {
      try {
        const response = await axios.get('/api/settings');
        this.businessName = response.data.business_name;
      } catch (error) {
        console.error('Error fetching business info:', error);
      }
    },

    updateDateTime() {
      this.currentDateTime = new Date().toLocaleString();
    },

    async init() {
      await Promise.all([
        this.fetchSettings(),
        this.fetchSalesData()
      ]);
    },

    handleDateChange() {
      console.log('Date range changed:', this.dateRange);
      this.fetchSalesData();
    },

    toggleDateDropdown(event) {
      event.stopPropagation(); // Prevent event bubbling
      this.showDateDropdown = !this.showDateDropdown;
      this.showExportDropdown = false; // Close other dropdown
    },

    toggleExportDropdown() {
      console.log('Toggle export dropdown'); // Debug log
      this.showExportDropdown = !this.showExportDropdown;
      if (this.showDateDropdown) {
        this.showDateDropdown = false;
      }
    },

    selectDateRange(range) {
      const today = new Date();
      let start = new Date();
      let end = new Date();

      switch (range) {
        case 'today':
          this.selectedRange = 'Today';
          break;

        case 'yesterday':
          start.setDate(today.getDate() - 1);
          end = new Date(start);
          this.selectedRange = 'Yesterday';
          break;

        case 'thisWeek':
          start.setDate(today.getDate() - today.getDay());
          this.selectedRange = 'This Week';
          break;

        case 'thisMonth':
          start = new Date(today.getFullYear(), today.getMonth(), 1);
          end = new Date(today.getFullYear(), today.getMonth() + 1, 0);
          this.selectedRange = 'This Month';
          break;

        case 'thisYear':
          start = new Date(today.getFullYear(), 0, 1);
          end = new Date(today.getFullYear(), 11, 31);
          this.selectedRange = 'This Year';
          break;

        case 'custom':
          this.showCustomRange = true;
          this.selectedRange = 'Custom Range';
          return;
      }

      this.dateRange = {
        start: start.toISOString().split('T')[0],
        end: end.toISOString().split('T')[0]
      };
      
      this.showDateDropdown = false;
      this.showCustomRange = false;
      this.fetchSalesData();
    },

    applyCustomRange() {
      this.showDateDropdown = false;
      this.showCustomRange = false;
      this.fetchSalesData();
    },

    handleClickOutside(event) {
      if (!event.target.closest('.dropdown')) {
        this.showDateDropdown = false;
      }
    }
  },

  watch: {
    // Watch for changes in businessName
    businessName(newVal) {
      console.log('Business name changed:', newVal);
    }
  },

  async created() {
    this.setUserName();
    if (localStorage.getItem('businessName')) {
      this.businessName = localStorage.getItem('businessName');
      this.currency = localStorage.getItem('currency');
    }
    await this.init();
  },

  mounted() {
    if (!this.userName) {
      this.setUserName();
    }
    
    if (!this.businessName || !this.currency) {
      this.fetchSettings();
    }

    if (this.salesData.length === 0) {
      this.fetchSalesData();
    }
    
    this.updateDateTime();
    this.timeInterval = setInterval(this.updateDateTime, 60000);
    document.addEventListener('click', this.handleClickOutside);
    this.selectDateRange('today'); // Default to today

    // Close dropdowns when clicking outside
    document.addEventListener('click', (e) => {
      if (!e.target.closest('.date-filter')) {
        this.showDateDropdown = false;
      }
      if (!e.target.closest('.export-filter')) {
        this.showExportDropdown = false;
      }
    });
  },

  beforeUnmount() {
    if (this.timeInterval) {
      clearInterval(this.timeInterval);
    }
    document.removeEventListener('click', this.handleClickOutside);
  }
}
</script>