<template>
  <div class="purchase-report-container">
    <!-- Business Info Section -->
    <div class="business-info">
      <h1 class="business-name">{{ businessName }}</h1>
      <p class="report-meta">Generated by: {{ userName }} | {{ currentDateTime }}</p>
    </div>

    <!-- Controls Section -->
    <div class="controls-section">
      <!-- Date Range Dropdown -->
      <div class="date-filter" ref="dateDropdown">
        <button class="filter-btn" @click="toggleDateDropdown">
          <i class="fas fa-calendar-alt"></i>
          <span>{{ selectedRange }}</span>
          <i class="fas fa-chevron-down" :class="{ 'rotate': showDateDropdown }"></i>
        </button>
        
        <div v-show="showDateDropdown" class="dropdown-menu date-menu">
          <button 
            v-for="(label, range) in dateRanges" 
            :key="range"
            class="dropdown-item"
            :class="{ 'active': selectedRange === label }"
            @click="selectDateRange(range)"
          >
            {{ label }}
          </button>
          
          <div v-if="showCustomRange" class="custom-range">
            <div class="custom-range-header">Select Date Range</div>
            <div class="range-inputs">
              <div class="input-group">
                <label>Start Date</label>
                <input type="date" v-model="dateRange.start" :max="dateRange.end">
              </div>
              <div class="input-group">
                <label>End Date</label>
                <input type="date" v-model="dateRange.end" :min="dateRange.start">
              </div>
            </div>
            <button class="apply-btn" @click="applyCustomRange">Apply</button>
          </div>
        </div>
      </div>

      <!-- Export Dropdown -->
      <div class="export-filter" ref="exportDropdown">
        <button type="button" class="filter-btn export-btn" @click="toggleExportDropdown">
          <i class="fas fa-download"></i>
          <span>Export</span>
          <i class="fas fa-chevron-down" :class="{ 'rotate': showExportDropdown }"></i>
        </button>
        
        <div v-show="showExportDropdown" class="dropdown-menu export-menu">
          <button type="button" class="dropdown-item" @click="handleExportToPDF">
            <i class="fas fa-file-pdf"></i>
            <span>Export to PDF</span>
          </button>
          <button type="button" class="dropdown-item" @click="handleExportToExcel">
            <i class="fas fa-file-excel"></i>
            <span>Export to Excel</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
      <div class="summary-card">
        <i class="fas fa-shopping-cart summary-icon"></i>
        <div class="summary-details">
          <h3>Total Purchases</h3>
          <p class="summary-value">{{ totalPurchases }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-box summary-icon"></i>
        <div class="summary-details">
          <h3>Total Products</h3>
          <p class="summary-value">{{ totalProducts }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-money-bill-wave summary-icon"></i>
        <div class="summary-details">
          <h3>Total Amount</h3>
          <p class="summary-value">{{ formatCurrency(totalAmount) }}</p>
        </div>
      </div>

      <div class="summary-card">
        <i class="fas fa-hand-holding-usd summary-icon"></i>
        <div class="summary-details">
          <h3>Total Due</h3>
          <p class="summary-value">{{ formatCurrency(totalDue) }}</p>
        </div>
      </div>
    </div>

    <!-- Data Table -->
    <div class="table-container">
      <table class="data-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Purchases</th>
            <th>Products</th>
            <th>Total Amount</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
          </tr>
        </thead>
        <tbody v-if="!loading && purchaseData.length">
          <tr v-for="row in purchaseData" :key="row.purchase_date">
            <td>{{ formatDate(row.purchase_date) }}</td>
            <td>{{ row.purchase_count }}</td>
            <td>{{ row.products_purchased }}</td>
            <td>{{ formatCurrency(row.total_amount) }}</td>
            <td>{{ formatCurrency(row.paid_amount) }}</td>
            <td>{{ formatCurrency(row.due_amount) }}</td>
          </tr>
        </tbody>
        <tbody v-else-if="loading">
          <tr>
            <td colspan="6" class="loading-state">Loading data...</td>
          </tr>
        </tbody>
        <tbody v-else>
          <tr>
            <td colspan="6" class="no-data-state">No purchase data available</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export default {
  data() {
    return {
      businessName: localStorage.getItem('businessName') || '',
      currency: localStorage.getItem('currency') || '',
      userName: window.Laravel?.user?.name || 'Unknown User',
      currentDateTime: new Date().toLocaleString(),
      purchaseData: [],
      loading: false,
      showDateDropdown: false,
      showExportDropdown: false,
      showCustomRange: false,
      selectedRange: 'Today',
      dateRange: {
        start: new Date().toISOString().split('T')[0],
        end: new Date().toISOString().split('T')[0]
      },
      dateRanges: {
        today: 'Today',
        yesterday: 'Yesterday',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        thisYear: 'This Year',
        custom: 'Custom Range'
      }
    }
  },

  computed: {
    totalPurchases() {
      return this.purchaseData.reduce((sum, row) => sum + row.purchase_count, 0);
    },
    totalProducts() {
      return this.purchaseData.reduce((sum, row) => sum + row.products_purchased, 0);
    },
    totalAmount() {
      return this.purchaseData.reduce((sum, row) => sum + row.total_amount, 0);
    },
    totalDue() {
      return this.purchaseData.reduce((sum, row) => sum + row.due_amount, 0);
    }
  },

  methods: {
    formatCurrency(amount) {
      try {
        return new Intl.NumberFormat('en-KE', {
          style: 'currency',
          currency: this.currency || 'KES'
        }).format(amount);
      } catch (error) {
        return `${this.currency} ${amount}`;
      }
    },

    formatDate(date) {
      try {
        return new Date(date).toLocaleDateString();
      } catch (error) {
        return date;
      }
    },

    toggleDateDropdown() {
      this.showDateDropdown = !this.showDateDropdown;
      if (this.showExportDropdown) {
        this.showExportDropdown = false;
      }
    },

    toggleExportDropdown() {
      this.showExportDropdown = !this.showExportDropdown;
      if (this.showDateDropdown) {
        this.showDateDropdown = false;
      }
    },

    selectDateRange(range) {
      const today = new Date();
      let start = new Date();
      let end = new Date();

      switch (range) {
        case 'today':
          this.selectedRange = 'Today';
          break;

        case 'yesterday':
          start.setDate(today.getDate() - 1);
          end = new Date(start);
          this.selectedRange = 'Yesterday';
          break;

        case 'thisWeek':
          start.setDate(today.getDate() - today.getDay());
          this.selectedRange = 'This Week';
          break;

        case 'thisMonth':
          start = new Date(today.getFullYear(), today.getMonth(), 1);
          end = new Date(today.getFullYear(), today.getMonth() + 1, 0);
          this.selectedRange = 'This Month';
          break;

        case 'thisYear':
          start = new Date(today.getFullYear(), 0, 1);
          end = new Date(today.getFullYear(), 11, 31);
          this.selectedRange = 'This Year';
          break;

        case 'custom':
          this.showCustomRange = true;
          this.selectedRange = 'Custom Range';
          return;
      }

      this.dateRange = {
        start: start.toISOString().split('T')[0],
        end: end.toISOString().split('T')[0]
      };
      
      this.showDateDropdown = false;
      this.showCustomRange = false;
      this.fetchPurchaseData();
    },

    applyCustomRange() {
      this.showDateDropdown = false;
      this.showCustomRange = false;
      this.fetchPurchaseData();
    },

    handleClickOutside(event) {
      const dateDropdown = this.$refs.dateDropdown;
      const exportDropdown = this.$refs.exportDropdown;

      if (dateDropdown && !dateDropdown.contains(event.target)) {
        this.showDateDropdown = false;
      }
      if (exportDropdown && !exportDropdown.contains(event.target)) {
        this.showExportDropdown = false;
      }
    },

    async handleExportToPDF() {
      try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        
        // Add business header
        doc.setFontSize(16);
        const businessText = this.businessName || 'Purchase Report';
        const textWidth = doc.getTextWidth(businessText);
        const xPosition = (pageWidth - textWidth) / 2;
        doc.text(businessText, xPosition, 20);
        
        // Add metadata
        doc.setFontSize(10);
        doc.text(`Generated by: ${this.userName}`, 15, 30);
        doc.text(`Date: ${new Date().toLocaleString()}`, 15, 35);
        
        // Add summary section
        doc.setFontSize(12);
        doc.text('Summary', 15, 45);
        
        const summaryData = [
          ['Total Purchases', this.totalPurchases.toString()],
          ['Total Products', this.totalProducts.toString()],
          ['Total Amount', this.formatCurrency(this.totalAmount)],
          ['Total Due', this.formatCurrency(this.totalDue)]
        ];

        doc.autoTable({
          startY: 50,
          head: [['Metric', 'Value']],
          body: summaryData,
          theme: 'grid',
          styles: { fontSize: 10 },
          headStyles: { fillColor: [33, 150, 243] }
        });

        // Add main data table
        const tableData = this.purchaseData.map(row => [
          this.formatDate(row.purchase_date),
          row.purchase_count.toString(),
          row.products_purchased.toString(),
          this.formatCurrency(row.total_amount),
          this.formatCurrency(row.paid_amount),
          this.formatCurrency(row.due_amount)
        ]);

        doc.autoTable({
          startY: doc.previousAutoTable.finalY + 15,
          head: [['Date', 'Purchases', 'Products', 'Total', 'Paid', 'Due']],
          body: tableData,
          theme: 'grid',
          styles: { fontSize: 8 },
          headStyles: { fillColor: [33, 150, 243] }
        });

        const fileName = `${this.businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_purchase_report_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);
        this.showExportDropdown = false;
      } catch (error) {
        console.error('PDF export failed:', error);
        alert('Failed to export PDF. Please try again.');
      }
    },

    async handleExportToExcel() {
      try {
        const wb = XLSX.utils.book_new();
        
        // Add summary worksheet
        const summaryData = [
          ['Business Name:', this.businessName],
          ['Generated By:', this.userName],
          ['Date:', new Date().toLocaleString()],
          [''],
          ['Summary'],
          ['Total Purchases:', this.totalPurchases],
          ['Total Products:', this.totalProducts],
          ['Total Amount:', this.formatCurrency(this.totalAmount)],
          ['Total Due:', this.formatCurrency(this.totalDue)]
        ];
        
        const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
        XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

        // Add details worksheet
        const wsData = this.purchaseData.map(row => ({
          'Date': this.formatDate(row.purchase_date),
          'Purchases': row.purchase_count,
          'Products': row.products_purchased,
          'Total Amount': this.formatCurrency(row.total_amount),
          'Paid Amount': this.formatCurrency(row.paid_amount),
          'Due Amount': this.formatCurrency(row.due_amount)
        }));
        
        const wsDetails = XLSX.utils.json_to_sheet(wsData);
        XLSX.utils.book_append_sheet(wb, wsDetails, "Details");

        const fileName = `${this.businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_purchase_report_${new Date().toISOString().split('T')[0]}.xlsx`;
        XLSX.writeFile(wb, fileName);
        
        this.showExportDropdown = false;
      } catch (error) {
        console.error('Excel export failed:', error);
        alert('Failed to export Excel file. Please try again.');
      }
    },

    async fetchPurchaseData() {
      try {
        this.loading = true;
        const response = await axios.get('/api/purchase-report-api', {
          params: {
            start_date: this.dateRange.start,
            end_date: this.dateRange.end
          }
        });

        if (Array.isArray(response.data)) {
          this.purchaseData = response.data;
        } else {
          console.error('Unexpected response format:', response.data);
          this.purchaseData = [];
        }
      } catch (error) {
        console.error('Error fetching purchase data:', error);
        this.purchaseData = [];
      } finally {
        this.loading = false;
      }
    }
  },

  mounted() {
    // Get user info from window.Laravel
    if (window.Laravel && window.Laravel.user) {
      this.userName = window.Laravel.user.name;
    }
    
    document.addEventListener('click', this.handleClickOutside);
    this.fetchPurchaseData();
  },

  beforeUnmount() {
    document.removeEventListener('click', this.handleClickOutside);
  }
}
</script>


<style scoped>
.sales-report-container {
  background: #ffffff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  padding: 24px;
  margin: 24px;
}

/* Header Styling */
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 32px;
}

.title-section {
  display: flex;
  flex-direction: column;
}

.title {
  font-size: 24px;
  font-weight: 600;
  color: #2c3e50;
  margin: 0;
}

.subtitle {
  color: #6c757d;
  margin: 4px 0 0 0;
  font-size: 14px;
}

/* Export Button Styling */
.export-dropdown {
  position: relative;
  z-index: 1000;
}

.export-button {
  background: #2196F3;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 2px 4px rgba(33, 150, 243, 0.2);
  white-space: nowrap;
}

.export-button:hover {
  background: #1976D2;
  transform: translateY(-1px);
  box-shadow: 0 4px 8px rgba(33, 150, 243, 0.3);
}

.fa-chevron-down {
  transition: transform 0.3s ease;
}

.fa-chevron-down.rotate {
  transform: rotate(180deg);
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  right: 0;
  margin-top: 8px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  min-width: 200px;
  border: 1px solid rgba(0, 0, 0, 0.1);
  z-index: 1001;
}

.dropdown-item {
  display: flex;
  align-items: center;
  width: 100%;
  padding: 12px 16px;
  border: none;
  background: none;
  color: #2c3e50;
  cursor: pointer;
  transition: all 0.2s ease;
  text-align: left;
}

.dropdown-item:hover {
  background: #f0f7ff;
  color: #2196F3;
}

.dropdown-item:not(:last-child) {
  border-bottom: 1px solid #eee;
}

/* Fade transition */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

/* Filters Section */
.filters-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
  margin-bottom: 32px;
}

.filter-label {
  display: block;
  margin-bottom: 8px;
  color: #2c3e50;
  font-weight: 500;
  font-size: 14px;
}

.filter-select, .date-input, .search-input {
  width: 100%;
  padding: 10px 16px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  font-size: 14px;
  color: #2c3e50;
  transition: all 0.3s ease;
}

.filter-select:focus, .date-input:focus, .search-input:focus {
  border-color: #4CAF50;
  outline: none;
  box-shadow: 0 0 0 3px rgba(76, 175, 80, 0.1);
}

.search-input-wrapper {
  position: relative;
}

.search-icon {
  position: absolute;
  left: 16px;
  top: 50%;
  transform: translateY(-50%);
  color: #6c757d;
}

.search-input {
  padding-left: 44px;
}

/* Table Styling */
.table-wrapper {
  overflow-x: auto;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.table-header {
  background: #f8f9fa;
  padding: 16px;
  font-weight: 600;
  color: #2c3e50;
  text-align: left;
  cursor: pointer;
  transition: background 0.2s ease;
}

.table-header:hover {
  background: #e9ecef;
}

.header-content {
  display: flex;
  align-items: center;
  gap: 8px;
}

.sort-icon {
  color: #4CAF50;
}

tbody tr {
  border-bottom: 1px solid #e2e8f0;
}

tbody tr:last-child {
  border-bottom: none;
}

td {
  padding: 16px;
  color: #2c3e50;
}

tbody tr:hover {
  background: #f8f9fa;
}

@media (max-width: 768px) {
  .header {
    flex-direction: column;
    align-items: stretch;
    gap: 16px;
  }

  .export-dropdown {
    width: 100%;
  }

  .export-button {
    width: 100%;
    justify-content: center;
  }

  .dropdown-menu {
    width: 100%;
  }
}

/* Ensure dropdown is visible */
.export-dropdown {
  position: relative !important;
}

.dropdown-menu {
  display: block;
  visibility: visible;
  opacity: 1;
}

/* Debug styles */
.dropdown-menu[style*="display: none"] {
  display: block !important;
  visibility: hidden;
  opacity: 0;
}

.dropdown-menu {
  background: red !important;
  z-index: 9999 !important;
  position: fixed !important;
  top: 100px !important;
  right: 100px !important;
}

.business-info {
  text-align: center;
  margin-bottom: 2rem;
}

.business-name {
  font-size: 2rem;
  color: #2c3e50;
  margin-bottom: 0.5rem;
}

.report-meta {
  color: #6c757d;
  font-size: 0.9rem;
}

.summary-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.summary-card {
  background: white;
  border-radius: 10px;
  padding: 1.5rem;
  display: flex;
  align-items: center;
  gap: 1rem;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  transition: transform 0.2s ease;
}

.summary-card:hover {
  transform: translateY(-2px);
}

.summary-icon {
  font-size: 2rem;
  color: #2196F3;
  background: rgba(33, 150, 243, 0.1);
  padding: 1rem;
  border-radius: 50%;
}

.summary-details h3 {
  margin: 0;
  font-size: 0.9rem;
  color: #6c757d;
}

.summary-value {
  margin: 0.25rem 0 0;
  font-size: 1.5rem;
  font-weight: 600;
  color: #2c3e50;
}

@media (max-width: 768px) {
  .summary-section {
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  }
}

.data-table-container {
  margin-top: 2rem;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.data-table th,
.data-table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #eee;
}

.data-table th {
  background: #f8f9fa;
  font-weight: 600;
  color: #2c3e50;
}

.data-table tbody tr:hover {
  background: #f8f9fa;
}

.data-table tfoot {
  font-weight: 600;
  background: #f8f9fa;
}

.loading-state,
.no-data-state {
  text-align: center;
  padding: 2rem;
  color: #6c757d;
  font-style: italic;
}

.controls-section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1.5rem;
  position: relative;
}

.date-filter, .export-filter {
  position: relative;
}

.filter-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  font-size: 0.875rem;
  color: #333;
  cursor: pointer;
  min-width: 150px;
  justify-content: space-between;
}

.export-btn {
  background: #2196F3;
  color: white;
  border: none;
}

.dropdown-menu {
  position: absolute;
  top: calc(100% + 0.25rem);
  left: 0;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  z-index: 1000;
}

.date-menu {
  width: 240px;
}

.export-menu {
  width: 100%;
  min-width: 180px;
}

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.5rem 1rem;
  border: none;
  background: none;
  text-align: left;
  font-size: 0.875rem;
  color: #333;
  cursor: pointer;
}

.dropdown-item:hover {
  background: #f5f5f5;
}

.dropdown-item.active {
  background: #e3f2fd;
  color: #2196F3;
}

.custom-range {
  border-top: 1px solid #ddd;
  padding: 1rem;
  background: #f8f9fa;
}

.custom-range-header {
  font-weight: 500;
  margin-bottom: 0.75rem;
  color: #333;
}

.range-inputs {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.input-group {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.input-group label {
  font-size: 0.75rem;
  color: #666;
}

.input-group input {
  padding: 0.375rem;
  border: 1px solid #ddd;
  border-radius: 0.25rem;
  font-size: 0.875rem;
}

.apply-btn {
  width: 100%;
  margin-top: 0.75rem;
  padding: 0.5rem;
  background: #2196F3;
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-size: 0.875rem;
}

.apply-btn:hover {
  background: #1976D2;
}

.rotate {
  transform: rotate(180deg);
}

@media (max-width: 768px) {
  .controls-section {
    flex-direction: column;
  }

  .date-filter, .export-filter {
    width: 100%;
  }

  .filter-btn {
    width: 100%;
  }

  .dropdown-menu {
    width: 100%;
  }
}

/* Update these specific styles */
.export-filter {
  position: relative;
  display: inline-block;
}

.export-btn {
  min-width: 120px; /* Adjust this value based on your needs */
  white-space: nowrap;
}

.export-menu {
  position: absolute;
  top: 100%;
  right: 0; /* Align to right */
  width: 100%; /* Match button width */
  min-width: fit-content;
  background: white;
  border: 1px solid #ddd;
  border-radius: 0.375rem;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  z-index: 1000;
  margin-top: 0.25rem;
}

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  width: 100%;
  border: none;
  background: none;
  text-align: left;
  cursor: pointer;
  white-space: nowrap;
}

.dropdown-item:hover {
  background: #f5f5f5;
}
</style>